version: '3'

services:
  mongodb:
    build: 
      context: .
      dockerfile: Dockerfile.bdd
    ports:
      - "27017:27017"

  scrapping:
    build: 
      context: .
      dockerfile: Dockerfile.scrapping
    depends_on:
      - mongodb

  dash:
    build: 
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8050:8050"
    depends_on:
      - mongodb


